# Site settings
title: UlamPinoy
email: chef@ulampinoy.com
description: Ulam Pinoy is a labour of love for home cooking, food photography and video recipes.
url: "http://ulampinoy.com" # the base hostname & protocol for your site
twitter_username: UlamPinoy

baseurl: ""

paginate: 8

# Build settings
kramdown:
  input: GFM
highlighter: pygments
relative_permalinks: false

# About/contact
author:
  name: Chef Ulam
  email: chef@ulampinoy.com

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :compressed # You might prefer to minify using :compressed

exclude: ["Gemfile", "Gemfile.lock", "README.md"]

collections:
  docs:
    output: true

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      permalink: /:year/:month/:title
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "docs"
